
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDAND COMMA EQ FROM GE GT IDENTIFIER LE LT NE NUMBER OR SELECT SEMICOLON STAR STRING WHEREquery : SELECT select_list FROM IDENTIFIER where_clause_opt SEMICOLONselect_list : STARselect_list : column_listcolumn_list : IDENTIFIERcolumn_list : column_list COMMA IDENTIFIERwhere_clause_opt : WHERE condition\n                            | emptycondition : condition AND condition\n                     | condition OR conditioncondition : comparisoncomparison : IDENTIFIER operator literaloperator : EQ\n                    | NE\n                    | GT\n                    | LT\n                    | GE\n                    | LEliteral : NUMBERliteral : STRINGempty :'
    
_lr_action_items = {'SELECT':([0,],[2,]),'$end':([1,14,],[0,-1,]),'STAR':([2,],[5,]),'IDENTIFIER':([2,7,8,12,18,19,],[4,9,10,17,17,17,]),'FROM':([3,4,5,6,10,],[7,-4,-2,-3,-5,]),'COMMA':([4,6,10,],[-4,8,-5,]),'WHERE':([9,],[12,]),'SEMICOLON':([9,11,13,15,16,27,28,29,30,31,],[-20,14,-7,-6,-10,-8,-9,-11,-18,-19,]),'AND':([15,16,27,28,29,30,31,],[18,-10,-8,18,-11,-18,-19,]),'OR':([15,16,27,28,29,30,31,],[19,-10,-8,-9,-11,-18,-19,]),'EQ':([17,],[21,]),'NE':([17,],[22,]),'GT':([17,],[23,]),'LT':([17,],[24,]),'GE':([17,],[25,]),'LE':([17,],[26,]),'NUMBER':([20,21,22,23,24,25,26,],[30,-12,-13,-14,-15,-16,-17,]),'STRING':([20,21,22,23,24,25,26,],[31,-12,-13,-14,-15,-16,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_list':([2,],[3,]),'column_list':([2,],[6,]),'where_clause_opt':([9,],[11,]),'empty':([9,],[13,]),'condition':([12,18,19,],[15,27,28,]),'comparison':([12,18,19,],[16,16,16,]),'operator':([17,],[20,]),'literal':([20,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> SELECT select_list FROM IDENTIFIER where_clause_opt SEMICOLON','query',6,'p_query','sql_parser.py',19),
  ('select_list -> STAR','select_list',1,'p_select_list_star','sql_parser.py',23),
  ('select_list -> column_list','select_list',1,'p_select_list_columns','sql_parser.py',27),
  ('column_list -> IDENTIFIER','column_list',1,'p_column_list_single','sql_parser.py',31),
  ('column_list -> column_list COMMA IDENTIFIER','column_list',3,'p_column_list_multi','sql_parser.py',35),
  ('where_clause_opt -> WHERE condition','where_clause_opt',2,'p_where_clause_opt','sql_parser.py',39),
  ('where_clause_opt -> empty','where_clause_opt',1,'p_where_clause_opt','sql_parser.py',40),
  ('condition -> condition AND condition','condition',3,'p_condition_visual','sql_parser.py',47),
  ('condition -> condition OR condition','condition',3,'p_condition_visual','sql_parser.py',48),
  ('condition -> comparison','condition',1,'p_condition_comparison','sql_parser.py',52),
  ('comparison -> IDENTIFIER operator literal','comparison',3,'p_comparison','sql_parser.py',56),
  ('operator -> EQ','operator',1,'p_operator','sql_parser.py',60),
  ('operator -> NE','operator',1,'p_operator','sql_parser.py',61),
  ('operator -> GT','operator',1,'p_operator','sql_parser.py',62),
  ('operator -> LT','operator',1,'p_operator','sql_parser.py',63),
  ('operator -> GE','operator',1,'p_operator','sql_parser.py',64),
  ('operator -> LE','operator',1,'p_operator','sql_parser.py',65),
  ('literal -> NUMBER','literal',1,'p_literal_number','sql_parser.py',69),
  ('literal -> STRING','literal',1,'p_literal_string','sql_parser.py',73),
  ('empty -> <empty>','empty',0,'p_empty','sql_parser.py',77),
]
